version: 2.1
jobs:
  test-go:
    # Install go modules and run tests
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - restore_cache:
          key: go-mod-{{ checksum "go.sum" }}
      - run:
          name: Download Go modules
          command: go mod download
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - run:
          name: Run tests
          command: gotestsum --junitfile junit.xml -- -coverprofile=cover.out ./...
      - run:
          name: Save html coverage
          command: go tool cover -html=cover.out -o cover.html
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: cover.html
workflows:
  test:
    jobs:
      - test-go
